<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>async与await</title>
</head>
<body>
    <script>
/*  1. async 函数
        函数的返回值为promise 对象
        promise 对象的结果由async 函数执行的返回值决定
    2. await 表达式
        await 右侧的表达式一般为promise 对象, 但也可以是其它的值
        如果表达式是promise 对象, await 返回的是promise 成功的值
    3. 注意：
        await必须写在async函数中，但async函数中可以没有await
        如果await 的promise 失败了, 就会抛出异常, 需要通过try...catch 捕获处理
*/
//async函数返回的是一个promise 对象
async function fn1(){
    // return 1;
    // throw 2;
    // return Promise.reject(3);
    // return Promise.resolve(3);
    return new Promise((resolve, reject)=>{
        setTimeout(()=>{
            resolve(4)
        }, 1000);
    })

}
const result = fn1();
// console.log(result);
result.then(
    value =>{
        console.log('onResolved()', value);
    },
    reason =>{
        console.log('onRejected()', reason);
    }
)
function fn2(){
    return new Promise((resolve, reject)=>{
        setTimeout(()=>{
            // resolve(5);
            reject(6);
        }, 1000);
    })
}
function fn4(){
    return 6;
}

async function fn3(){
    try{
        // const value = await fn2(); //await右侧表达式promise, 得到的结果就是promise成功的value
        // const value = await fn4();//await右侧表达不是promise ,得到的结果就是这个值本身
        const value = await fn1();
        console.log('value', value);
    }catch(error){
        console.log('得到失败的结果',error);
    }
}
fn3();
    </script>
</body>
</html>